/*
 * Copyright 2026 Antonio Cantallops Alba
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
use crate::parse::{parse_serverfile, ServerfileAst};
use exyonq_config_ir::DEFAULT_UPSTREAM_TIMEOUT_MS;

#[derive(Debug, Clone, Default)]
pub struct CompileOptions {
    pub profile: Option<exyonq_config_merge::Profile>,
    pub generated_comment: bool,
}

pub fn compile_serverfile(input: &str, opts: CompileOptions) -> Result<String, CompileError> {
    let ast = parse_serverfile(input).map_err(CompileError::Parse)?;
    let mut toml = lower(&ast, opts.generated_comment);
    if let Some(profile) = opts.profile {
        let config = exyonq_config_ir::AppConfig::parse_str(&toml).map_err(CompileError::Ir)?;
        let config = exyonq_config_merge::apply_profile(config, profile);
        toml = exyonq_config_schema::render_toml_public(&config).map_err(CompileError::Ir)?;
    }
    Ok(toml)
}

#[derive(Debug, thiserror::Error)]
pub enum CompileError {
    #[error(transparent)]
    Parse(#[from] crate::parse::ParseError),
    #[error(transparent)]
    Ir(#[from] exyonq_config_ir::ConfigError),
}

impl CompileError {
    pub fn to_diagnostic(&self) -> exyonq_config_ir::Diagnostic {
        match self {
            Self::Parse(e) => e.to_diagnostic(),
            Self::Ir(e) => {
                let mut d = e.to_diagnostic();
                if matches!(
                    d.code,
                    exyonq_config_ir::DiagnosticCode::IrValidationError
                        | exyonq_config_ir::DiagnosticCode::UnknownField
                ) {
                    // lowering path may surface IR errors as surface lowering failures
                    if d.code == exyonq_config_ir::DiagnosticCode::IrValidationError {
                        d.code = exyonq_config_ir::DiagnosticCode::SurfaceLoweringError;
                    }
                }
                d
            }
        }
    }
}

fn lower(ast: &ServerfileAst, generated_comment: bool) -> String {
    let listen = normalize_listen(&ast.listener);
    let mut out = String::from("config_version = 1\n");
    if generated_comment {
        out.push_str("# generated by exyonq compile\n");
    }
    out.push('\n');
    out.push_str("[[server]]\n");
    out.push_str(&format!("listen = {listen:?}\n"));
    let route_names: Vec<String> = ast
        .routes
        .iter()
        .enumerate()
        .map(|(i, r)| route_name(i, &r.path))
        .collect();
    out.push_str("routes = [");
    for (i, name) in route_names.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{name:?}"));
    }
    out.push_str("]\n\n");

    for (i, route) in ast.routes.iter().enumerate() {
        let name = route_name(i, &route.path);
        out.push_str("[[route]]\n");
        out.push_str(&format!("name = {name:?}\n"));
        out.push_str(&format!("match = {{ path = {:?} }}\n", route.path));
        if let Some(proxy) = &route.proxy {
            out.push_str(&format!("upstream = {:?}\n", proxy.upstream_name));
        }
        if let Some(root) = &route.root {
            out.push_str(&format!("root = {root:?}\n"));
        }
        if let Some(index) = &route.index {
            out.push_str(&format!("index = {index:?}\n"));
        }
        out.push('\n');
    }

    let mut upstreams = Vec::new();
    for route in &ast.routes {
        if let Some(proxy) = &route.proxy {
            if !upstreams.iter().any(|(n, _)| n == &proxy.upstream_name) {
                upstreams.push((proxy.upstream_name.clone(), proxy));
            }
        }
    }
    for (name, proxy) in upstreams {
        let timeout = proxy.timeout_ms.unwrap_or(DEFAULT_UPSTREAM_TIMEOUT_MS);
        out.push_str("[[upstream]]\n");
        out.push_str(&format!("name = {name:?}\n"));
        out.push_str(&format!("target = \"http://127.0.0.1:{}\"\n", proxy.port));
        if timeout != DEFAULT_UPSTREAM_TIMEOUT_MS {
            out.push_str(&format!("timeout_ms = {timeout}\n"));
        }
        out.push('\n');
    }

    if ast.metrics {
        out.push_str("[modules.metrics]\nenabled = true\n\n");
    }
    if ast.compression {
        out.push_str("[modules.compression]\nenabled = true\n\n");
    }
    if let Some((rps, burst)) = ast.ratelimit {
        out.push_str("[modules.ratelimit]\n");
        out.push_str(&format!(
            "enabled = true\nrequests_per_second = {rps}\nburst = {burst}\n\n"
        ));
    }
    out
}

fn normalize_listen(raw: &str) -> String {
    if raw.starts_with(':') {
        format!("0.0.0.0{}", raw)
    } else {
        raw.to_string()
    }
}

fn route_name(index: usize, path: &str) -> String {
    let slug = path.trim_matches('/').replace(['/', '.'], "_");
    if slug.is_empty() {
        format!("route{}", index + 1)
    } else {
        slug
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lowers_to_valid_ir() {
        let toml = compile_serverfile(
            r#"
:8080 {
    route /api {
        proxy backend 9000
    }
}
"#,
            CompileOptions::default(),
        )
        .unwrap();
        exyonq_config_ir::AppConfig::parse_str(&toml).unwrap();
    }
}
