docRoot                   /bench/www/
enableGzip                0
indexFiles                index.html

extprocessor upstream {
  type                    proxy
  address                 upstream:9000
  maxConns                10000
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
}

context /health {
  location                /bench/health.txt
  allowBrowse             1
}

context /site/ {
  location                /bench/www/
  allowBrowse             1
  indexFiles              index.html
}

context /api/ {
  type                    proxy
  handler                 upstream
  addDefaultCharset       off
  extraHeaders            X-Forwarded-For $REMOTE_ADDR
}
